name: Test Static Website

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t my-static-site .
    
    - name: Run container
      run: |
        docker run -d -p 8080:80 --name test-site my-static-site
        sleep 5  # Give container time to start
    
    - name: Test website is accessible
      run: |
        curl -f http://localhost:8080 || exit 1
        echo "Website is running successfully!"
    
    - name: Stop container
      run: docker stop test-site
